AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Forex Data Streaming Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  ProjectApiKey:
    Type: String
    Description: Finnhub API Key

Resources:
    ForexDataWebsocket:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ForexDataWebsocket
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.message"
    ConnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $connect
        AuthorizationType: NONE
        OperationName: ConnectRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref ConnectIntegration
    ConnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    DisconnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $disconnect
        AuthorizationType: NONE
        OperationName: DisconnectRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref DisconnectIntegration
    DisconnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    SubscribeRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: subscribe
        AuthorizationType: NONE
        OperationName: SubscribeRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref SubscribeIntegration
    SubscribeIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    UnsubscribeRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: unsubscribe
        AuthorizationType: NONE
        OperationName: UnsubscribeRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref UnsubscribeIntegration
    UnsubscribeIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    DefaultRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $default
        AuthorizationType: NONE
        OperationName: DefaultRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref DefaultIntegration
    DefaultIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    Deployment:
      Type: AWS::ApiGatewayV2::Deployment
      DependsOn:
        - ConnectRoute
        - SubscribeRoute
        - UnsubscribeRoute
        - DisconnectRoute
        - DefaultRoute
      Properties:
        ApiId: !Ref ForexDataWebsocket
    Stage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        StageName: Prod
        DeploymentId: !Ref Deployment
        ApiId: !Ref ForexDataWebsocket

    SymbolDataFunction:
      Type: AWS::Serverless::Function
      Properties:
        PackageType: Image
        FunctionName: SymbolDataFunction
        Environment:
            Variables:
              ProjectApiKey: !Ref ProjectApiKey
        Events:
          ScheduledFinnhubCall:
            Type: Schedule
            Properties:
              Schedule: rate(2 minutes)
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref SymbolRateTable
      Metadata:
        DockerTag: go1.x-v1
        DockerContext: ./technical-analysis-lambda
        Dockerfile: Dockerfile
    
    WebsocketMessageFunction:
      Type: AWS::Serverless::Function
      Properties:
        PackageType: Image
        FunctionName: WebsocketMessageFunction
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref WebsocketConnectionsTable
          - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForexDataWebsocket}/*'
          # - Version: '2012-10-17'
          #   Statement:
          #     - Effect: Allow
          #       Action:
          #         - dynamodb:DeleteItem
          #         - dynamodb:GetItem
          #         - dynamodb:PutItem
          #         - dynamodb:UpdateItem
          #       Resource:
          #         !Join
          #           - ''
          #           - - 'arn:aws:dynamodb:'
          #             - !Ref AWS::Region
          #             - ':'
          #             - !Ref AWS::AccountId
          #             - ':table/WebsocketConnectionsTable'
      Metadata:
        DockerTag: go1.x-v1
        DockerContext: ./websocket-server-lambda
        Dockerfile: Dockerfile
    WebsocketMessageFunctionPermission:
      Type: AWS::Lambda::Permission
      DependsOn:
        - ForexDataWebsocket
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref WebsocketMessageFunction
        Principal: apigateway.amazonaws.com

    SymbolRateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SymbolRateTable
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    WebsocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WebsocketConnectionsTable
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

Outputs:
  WebSocketURI:
    Value: !Join ['', ['wss://', !Ref ForexDataWebsocket, '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref 'Stage']]
